# Amigos SMP - Survival+
motd=§b§lAmigos SMP §8• §fSurvival+ com RPG leve
max-players=12
online-mode=true
difficulty=hard
gamemode=survival
pvp=true
spawn-protection=16
view-distance=8
simulation-distance=6
allow-flight=false
allow-nether=true
generate-structures=true
spawn-monsters=true
spawn-animals=true
white-list=false
enforce-whitelist=false
player-idle-timeout=0
level-name=world
level-seed=
resource-pack=
resource-pack-sha1=
require-resource-pack=false
